# Generated by Django 6.0.3 on 2026-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="matches_count",
            field=models.IntegerField(default=0),
        ),
    ]
