# Generated by Django 6.0.3 on 2026-03-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('tries', models.JSONField(default=list)),
                ('max_tries', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
            ],
        ),
    ]
