# Generated by Django 6.0.3 on 2026-04-05 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="", max_length=6)),
                ("is_win", models.BooleanField(default=False)),
                ("player", models.CharField(default="anon")),
                ("word", models.CharField(max_length=5)),
                ("tries", models.JSONField(default=list)),
                ("max_tries", models.IntegerField(default=6)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
            ],
        ),
    ]
