# Generated by Django 6.0.3 on 2026-03-26 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.CharField(default='anon'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.CharField(max_length=8),
        ),
    ]
