# Generated by Django 6.0.3 on 2026-04-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='code',
        ),
    ]
