# Generated by Django 6.0.3 on 2026-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_code_game_player_alter_game_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
    ]
