# Generated by Django 6.0.3 on 2026-04-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_code_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player",
            field=models.CharField(),
        ),
    ]
